In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

df = pd.read_csv('downloads/SaratogaHouses.csv')
x=df['livingArea'].values
y=df['price'].values

y


array([132500, 181115, 109000, ..., 194900, 125000, 111300])

In [5]:
x

array([ 906, 1953, 1944, ..., 1099, 1225, 1959])

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)
x_mean=np.mean(x_train)
y_mean=np.mean(y_train)
n=0
d=0
print(len(x_train))
print(len(y_train))
x_train

1296
1296


array([ 924, 2702, 2354, ..., 1944, 1812, 2244])

In [10]:
for i in range(len(y_train)):
    n+=(y_train[i]-y_mean)*(x_train[i]-x_mean)
    d+=(x_train[i]-x_mean)*(x_train[i]-x_mean)
    
slope=n/d
c=y_mean-slope*x_mean

reg=LinearRegression()
x_train=x_train.reshape(-1,1)
y_train=y_train.reshape(-1,1)
reg.fit(x_train,y_train)
x_test=x_test.reshape(-1,1) #-1 means rows are unknown and numpy will adjust them as per requirement
resultx=reg.predict(x_test)
resultx

array([[336700.575228  ],
       [199862.14892559],
       [361654.84303828],
       [181117.15902115],
       [181117.15902115],
       [300265.00110124],
       [229385.50802508],
       [113166.57061755],
       [308817.40274514],
       [125819.43880305],
       [165418.22997618],
       [121250.34751384],
       [204079.77165409],
       [230439.9137072 ],
       [134254.68426005],
       [283980.29112176],
       [165418.22997618],
       [277185.2322814 ],
       [151593.79992165],
       [263595.11460068],
       [112697.94586994],
       [369738.61993457],
       [235477.62974402],
       [204548.3964017 ],
       [119024.37996269],
       [243912.87520102],
       [270390.17344104],
       [298624.81448461],
       [210289.04955993],
       [128631.18728872],
       [152648.20560378],
       [135660.55850288],
       [195644.52619709],
       [114572.44486039],
       [131442.93577438],
       [150656.55042643],
       [203728.30309338],
       [177368.16104026],
       [1780

In [11]:
y_pred=slope*x_test+c

In [12]:
y_pred

array([[336700.575228  ],
       [199862.14892559],
       [361654.84303828],
       [181117.15902115],
       [181117.15902115],
       [300265.00110124],
       [229385.50802508],
       [113166.57061755],
       [308817.40274514],
       [125819.43880305],
       [165418.22997618],
       [121250.34751384],
       [204079.77165409],
       [230439.9137072 ],
       [134254.68426005],
       [283980.29112176],
       [165418.22997618],
       [277185.2322814 ],
       [151593.79992165],
       [263595.11460068],
       [112697.94586994],
       [369738.61993457],
       [235477.62974402],
       [204548.3964017 ],
       [119024.37996269],
       [243912.87520102],
       [270390.17344104],
       [298624.81448461],
       [210289.04955993],
       [128631.18728872],
       [152648.20560378],
       [135660.55850288],
       [195644.52619709],
       [114572.44486039],
       [131442.93577438],
       [150656.55042643],
       [203728.30309338],
       [177368.16104026],
       [1780